/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package base_de_données;

import application_gestion_de_stock.Parameter;
import application_gestion_de_stock.ResultSetTableModel;
import application_gestion_de_stock.Application_gestion_de_stock;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.Date;

public class Caisier extends javax.swing.JFrame {

    /**
     * Creates new form Cachier
     */
    ResultSet rs;
    Application_gestion_de_stock db;
    int old, dec, now;
    
    public Caisier() {
        db = new Application_gestion_de_stock(new Parameter().HOST_DB, new Parameter().USERNAME_DB,
                   new Parameter().PASSWORD_DB, new Parameter().IPHOST, new Parameter().PORT);
        initComponents();
        table();
        jam();
    }
       
    //fonction table
        public void table() {
         String a[] = {"code_produit", "reférence", "désignation", "rangement", "fournisseur", "remise", "prix","stock"};
         rs = db.querySelect(a, "produit");
         table_prod.setModel(new ResultSetTableModel(rs));    
        }
    //
    public void importer(){
        String colon[] = {"num_facture", "code_produit", "reference", "prix_vente", "stock_sortie", "subtotal"};
        rs = db.fcSelectCommand(colon, "vente", "num_facture='" +txt_fac.getText() + "'");
        table_vente.setModel(new ResultSetTableModel(rs));
    }    
    
    public void jam(){
        Date s = new Date();
        SimpleDateFormat tgl = new SimpleDateFormat("EEEE-dd-MM-yyyy");
        SimpleDateFormat jam = new SimpleDateFormat("HH:mm");
        lbl1.setText(jam.format(s));
        lbl2.setText(tgl.format(s));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_prod = new javax.swing.JTable();
        lbl2 = new javax.swing.JTextField();
        lbl1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        com_rech = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        txt_rech = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_cod = new javax.swing.JTextField();
        txt_ref = new javax.swing.JTextField();
        txt_ran = new javax.swing.JTextField();
        txt_fou = new javax.swing.JTextField();
        txt_pri = new javax.swing.JTextField();
        txt_rem = new javax.swing.JTextField();
        txt_nou = new javax.swing.JTextField();
        txt_sto = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        lbitot1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        txt_fac = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_vente = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        lbitot3 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lbitot2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txt_cash = new javax.swing.JTextField();
        txt_pay = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(720, 670));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("caisier");
        jLabel2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel2);
        jLabel2.setBounds(330, 10, 59, 40);

        table_prod.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "code_produit", "reférence", "désignation", "rangement", "fournisseur", "remise", "prix", "stock"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        table_prod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_prodMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_prod);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 60, 680, 90);

        lbl2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(lbl2);
        lbl2.setBounds(460, 10, 170, 30);

        lbl1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(lbl1);
        lbl1.setBounds(30, 10, 110, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 700, 160);

        jPanel2.setBackground(new java.awt.Color(153, 255, 102));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("recherche par categorie:");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(40, 10, 168, 17);

        com_rech.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        com_rech.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "code_produit", "reférence", "désignation", "rangement", "fournisseur", "remise", "prix", "stock" }));
        jPanel2.add(com_rech);
        com_rech.setBounds(40, 30, 160, 23);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("recherche");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(10, 60, 110, 30);

        txt_rech.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel2.add(txt_rech);
        txt_rech.setBounds(130, 60, 100, 30);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setText("code_produit:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(10, 110, 80, 14);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel4.setText("reférence:");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(10, 150, 60, 14);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel5.setText("rangement:");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(10, 180, 70, 14);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("fournisseur:");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(10, 220, 90, 14);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel7.setText("prix:");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(10, 260, 70, 14);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel8.setText("remise:");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(10, 300, 60, 14);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel9.setText("nouveau prix:");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(10, 330, 72, 14);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel10.setText("stock sortie:");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(10, 370, 64, 14);

        txt_cod.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jPanel2.add(txt_cod);
        txt_cod.setBounds(110, 110, 110, 21);

        txt_ref.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jPanel2.add(txt_ref);
        txt_ref.setBounds(110, 150, 110, 21);

        txt_ran.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        txt_ran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ranActionPerformed(evt);
            }
        });
        jPanel2.add(txt_ran);
        txt_ran.setBounds(110, 180, 110, 21);

        txt_fou.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jPanel2.add(txt_fou);
        txt_fou.setBounds(110, 220, 110, 21);

        txt_pri.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jPanel2.add(txt_pri);
        txt_pri.setBounds(110, 260, 110, 21);

        txt_rem.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jPanel2.add(txt_rem);
        txt_rem.setBounds(110, 300, 110, 21);

        txt_nou.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jPanel2.add(txt_nou);
        txt_nou.setBounds(109, 330, 110, 21);

        txt_sto.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        txt_sto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_stoKeyReleased(evt);
            }
        });
        jPanel2.add(txt_sto);
        txt_sto.setBounds(110, 370, 110, 21);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel11.setText("RP:");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(30, 420, 40, 14);

        lbitot1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbitot1.setText("0");
        jPanel2.add(lbitot1);
        lbitot1.setBounds(110, 414, 110, 20);

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton2.setText("Ajouter un produit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(20, 440, 190, 31);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 160, 240, 480);

        jTextField2.setText("jTextField2");
        getContentPane().add(jTextField2);
        jTextField2.setBounds(120, 260, 59, 20);

        jPanel3.setBackground(new java.awt.Color(0, 255, 51));
        jPanel3.setPreferredSize(new java.awt.Dimension(500, 420));
        jPanel3.setLayout(null);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel12.setText("num_facture:");
        jPanel3.add(jLabel12);
        jLabel12.setBounds(10, 70, 100, 17);

        txt_fac.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jPanel3.add(txt_fac);
        txt_fac.setBounds(110, 60, 80, 30);

        table_vente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "num_facture", "code_produit", "reference", "prix_vente", "stock_sortie", "subtotal"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(table_vente);

        jPanel3.add(jScrollPane2);
        jScrollPane2.setBounds(0, 100, 460, 90);

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton3.setText("recherche");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3);
        jButton3.setBounds(220, 60, 100, 25);

        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton4.setText("supprimer");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4);
        jButton4.setBounds(340, 60, 110, 25);

        lbitot3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbitot3.setText("RP");
        jPanel3.add(lbitot3);
        lbitot3.setBounds(220, 240, 80, 30);

        jLabel14.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel14.setText("Total:");
        jPanel3.add(jLabel14);
        jLabel14.setBounds(90, 240, 80, 22);

        lbitot2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbitot2.setText("0");
        jPanel3.add(lbitot2);
        lbitot2.setBounds(340, 240, 70, 30);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel13.setText("cash:");
        jPanel3.add(jLabel13);
        jLabel13.setBounds(50, 300, 50, 14);

        txt_cash.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        txt_cash.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_cashKeyReleased(evt);
            }
        });
        jPanel3.add(txt_cash);
        txt_cash.setBounds(120, 290, 80, 30);

        txt_pay.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jPanel3.add(txt_pay);
        txt_pay.setBounds(350, 290, 100, 30);

        jLabel16.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel16.setText("payé après:");
        jPanel3.add(jLabel16);
        jLabel16.setBounds(230, 287, 90, 30);

        jButton5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton5.setText("Imprimer");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton5);
        jButton5.setBounds(220, 360, 110, 31);

        jButton6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton6.setText("Annuler");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton6);
        jButton6.setBounds(220, 410, 110, 31);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(240, 160, 460, 480);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_ranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ranActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
         if(txt_rech.getText().equals("")){//si le textfield de recherche est vide le prog va affivher SVP entrer quelque chose
            JOptionPane.showMessageDialog(this, "SVP entrer quelque chose");
        }else{
            if(com_rech.getSelectedItem().equals("id")){
                rs = db.querySelectAll("produit", "id LIKE '%" + txt_rech.getText() + "%' ");
                table_prod.setModel(new ResultSetTableModel(rs));
            }else if(com_rech.getSelectedItem().equals("code_produit")){
                rs = db.querySelectAll("produit", "code_produit LIKE '%" + txt_rech.getText() + "%' ");
                table_prod.setModel(new ResultSetTableModel(rs));
            }else if(com_rech.getSelectedItem().equals("reférnce")){
                rs = db.querySelectAll("produit", "reférnce LIKE '%" + txt_rech.getText() + "%' ");
                table_prod.setModel(new ResultSetTableModel(rs));
            }else if(com_rech.getSelectedItem().equals("désignation")){
                rs = db.querySelectAll("produit", "désignation LIKE '%" + txt_rech.getText() + "%' ");
                table_prod.setModel(new ResultSetTableModel(rs));
            }else if(com_rech.getSelectedItem().equals("rangement")){
                rs = db.querySelectAll("produit", "rangement LIKE '%" + txt_rech.getText() + "%' ");
                table_prod.setModel(new ResultSetTableModel(rs));
            }else if(com_rech.getSelectedItem().equals("fournisseur")){
                rs = db.querySelectAll("produit", "fournisseur LIKE '%" + txt_rech.getText() + "%' ");
                table_prod.setModel(new ResultSetTableModel(rs));
            }else if(com_rech.getSelectedItem().equals("remise")){
                rs = db.querySelectAll("produit", "remise LIKE '%" + txt_rech.getText() + "%' ");
                table_prod.setModel(new ResultSetTableModel(rs));
            }else if(com_rech.getSelectedItem().equals("prix")){
                rs = db.querySelectAll("produit", "stock LIKE '%" + txt_rech.getText() + "%' ");
                table_prod.setModel(new ResultSetTableModel(rs));
            }else if(com_rech.getSelectedItem().equals("prix")){
                rs = db.querySelectAll("produit", "stock LIKE '%" + txt_rech.getText() + "%' ");
                table_prod.setModel(new ResultSetTableModel(rs));
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_stoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_stoKeyReleased
       subtotal();
    }//GEN-LAST:event_txt_stoKeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       if(txt_cod.getText().equals("") || txt_ref.getText().equals("") || txt_ran.getText().equals("")
                || txt_fou.getText().equals("") || txt_rem.getText().equals("") || txt_pri.getText().equals("") 
                || txt_nou.getText().equals("") || txt_sto.getText().equals("")){
            JOptionPane.showMessageDialog(this, "SVP entrer vos données");
        }else if (txt_fac.getText().equals("")){
            JOptionPane.showMessageDialog(this, "SVP entrer le numero de facture");
        }else{
            String[] colon = {"num_facture", "code_produit", "reference", "prix_vente", "stock_sortie", "subtotal"};
            String[] isl = {txt_fac.getText(), txt_cod.getText(), txt_ref.getText(), txt_nou.getText(), txt_sto.getText(), 
            lbitot1.getText()};
            System.out.println(db.queryInsert("vente", colon, isl));
            try{
                if (!test_stock()){
                    JOptionPane.showMessageDialog(this, "le stock est limité");
                }else{
                    def();
                    table();
                }
            }catch(SQLException ex){
                Logger.getLogger(Caisier.class.getName()).log(Level.SEVERE, null, ex);
                System.err.println("\n"+ex);
            }
            subtotal();
            importer();
            total();
        }
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        importer();
            total();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
     /*   String id = String.valueOf(table_vente.getValueAt(table_vente.getSelectedRow(), 0));
        if (JOptionPane.showConfirmDialog(this, "etes vous sur de vouloir supprimer", "Attention",
                JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION){
            db.queryDelete("vente", "id=" +id);
        }else{
            return;
        }
        importer();
        total();*/
       String invoice = txt_fac.getText();
       if(JOptionPane.showConfirmDialog(this, "etes vous sur de vouloir supprimer", "Attention", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION){
           db.queryDelete("vente", "num_facture=" + invoice);
       }else{
           return;
       }
       importer();
       total();
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txt_cashKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cashKeyReleased
        payaprès();
    }//GEN-LAST:event_txt_cashKeyReleased

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       Recu d = new Recu();
       d.setVisible(true);
       
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
       String invoice = txt_fac.getText();
       if(JOptionPane.showConfirmDialog(this, "etes vous sur de vouloir supprimer", "Attention", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION){
           db.queryDelete("vente", "num_facture=" + invoice);
       }else{
           return;
       }
       importer();
       total();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void table_prodMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_prodMouseClicked
        txt_cod.setText(String.valueOf(table_prod.getValueAt(table_prod.getSelectedRow(), 0)));
        txt_ref.setText(String.valueOf(table_prod.getValueAt(table_prod.getSelectedRow(), 1)));
        txt_ran.setText(String.valueOf(table_prod.getValueAt(table_prod.getSelectedRow(), 3)));
        txt_fou.setText(String.valueOf(table_prod.getValueAt(table_prod.getSelectedRow(), 4)));
        txt_rem.setText(String.valueOf(table_prod.getValueAt(table_prod.getSelectedRow(), 5)));
        txt_pri.setText(String.valueOf(table_prod.getValueAt(table_prod.getSelectedRow(), 6)));
      /*  txt_sto.setText(String.valueOf(table_prod.getValueAt(table_prod.getSelectedRow(), 6)));*/
        cout();
    }//GEN-LAST:event_table_prodMouseClicked

    public void subtotal(){
        double a = Double.parseDouble(txt_nou.getText());
        double b = Double.parseDouble(txt_sto.getText());
        double c = a * b;
        lbitot1.setText(String.valueOf(c));
    }
   
    public boolean test_stock() throws SQLException {
        boolean teststock;
        rs = db.querySelectAll("produit", "code_produit='" +txt_cod.getText() + "'");
        while (rs.next()){
            old = rs.getInt("stock");
        }
        dec = Integer.parseInt(txt_sto.getText());
        if (old < dec){
            teststock = false;
        }else{
            teststock = true;
        }
        return teststock;
    }
    
    public void def() throws SQLException {
        rs = db.querySelectAll("produit", "code_produit='" + txt_cod.getText() + "'");
        while(rs.next()){
            old = rs.getInt("stock");
        }
        dec = Integer.parseInt(txt_sto.getText());
        now = old - dec;
        String nvstock = Integer.toString(now);
        
        String a = String.valueOf(nvstock);
        String[] colon = {"stock"};
        String[] isl = {a};
        System.out.println(db.queryUpdate("produit", colon, isl, "code_produit='" + txt_cod.getText() + "'"));
    }
    
    public void total(){
        rs = db.executionQuery("SELECT SUM(subtotal) as subtotal FROM vente WHERE num_facture = '" + txt_fac.getText() + "'");
        try{
            rs.next();
            lbitot2.setText(rs.getString("subtotal"));
        }catch(SQLException ex){
            Logger.getLogger(Caisier.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void payaprès(){
        int a = Integer.parseInt(lbitot2.getText());
        int b = Integer.parseInt(txt_cash.getText());
        int c = b - a;
        txt_pay.setText(Integer.toString(c));
    }
    
    public void cout(){
        double a = Double.parseDouble(txt_pri.getText());
        double b = Double.parseDouble(txt_rem.getText());
        double c = a - a * (b/100);
        txt_nou.setText(String.valueOf(c));
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Caisier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Caisier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Caisier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Caisier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Caisier().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> com_rech;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel lbitot1;
    private javax.swing.JLabel lbitot2;
    private javax.swing.JLabel lbitot3;
    private javax.swing.JTextField lbl1;
    private javax.swing.JTextField lbl2;
    private javax.swing.JTable table_prod;
    private javax.swing.JTable table_vente;
    private javax.swing.JTextField txt_cash;
    private javax.swing.JTextField txt_cod;
    private javax.swing.JTextField txt_fac;
    private javax.swing.JTextField txt_fou;
    private javax.swing.JTextField txt_nou;
    private javax.swing.JTextField txt_pay;
    private javax.swing.JTextField txt_pri;
    private javax.swing.JTextField txt_ran;
    private javax.swing.JTextField txt_rech;
    private javax.swing.JTextField txt_ref;
    private javax.swing.JTextField txt_rem;
    private javax.swing.JTextField txt_sto;
    // End of variables declaration//GEN-END:variables
}
