/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package base_de_données;

import application_gestion_de_stock.Parameter;
import application_gestion_de_stock.ResultSetTableModel;
import application_gestion_de_stock.Application_gestion_de_stock;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Produit extends javax.swing.JFrame {

   ResultSet rs;
   Application_gestion_de_stock db;
   
    public Produit() {
        db = new Application_gestion_de_stock(new Parameter().HOST_DB, new Parameter().USERNAME_DB,
                   new Parameter().PASSWORD_DB, new Parameter().IPHOST, new Parameter().PORT);
        initComponents();
        table();
    }
    
    //fonction table
        public void table() {
         String a[] = {"code_produit", "reférence", "désignation", "rangement", "fournisseur", "remise", "prix","stock"};
         rs = db.querySelect(a, "produit");
         table_prod.setModel(new ResultSetTableModel(rs));    
        }
        
        
        void actualiser() {
            txt_co.setText("");
            txt_re.setText("");
            txt_de.setText("");
            txt_fo.setText("");
            txt_rm.setText("");
            txt_pr.setText("");
            txt_ra.setText("");
            txt_st.setText("");
            
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_prod = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_co = new javax.swing.JTextField();
        txt_re = new javax.swing.JTextField();
        txt_de = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_fo = new javax.swing.JTextField();
        txt_rm = new javax.swing.JTextField();
        txt_pr = new javax.swing.JTextField();
        com_rech = new javax.swing.JComboBox<String>();
        jButton5 = new javax.swing.JButton();
        txt_rech = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_ra = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_st = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 255, 51));
        setPreferredSize(new java.awt.Dimension(750, 420));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel1.setText("Gestion des produits");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(200, 10, 305, 44);

        table_prod.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "id", "code_produit", "reférence", "désignation", "rangement", "fournisseur", "remise", "prix", "stock"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_prod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_prodMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_prod);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 50, 700, 100);

        jButton1.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jButton1.setText("Ajouter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(10, 180, 100, 31);

        jButton2.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jButton2.setText("Modifier");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(120, 180, 97, 31);

        jButton3.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jButton3.setText("Supprimer");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(230, 180, 109, 31);

        jButton4.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jButton4.setText("Actualiser");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(350, 180, 107, 31);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("code_produit:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 250, 90, 17);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("reference:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 280, 90, 17);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("désignation:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 310, 90, 17);

        txt_co.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        getContentPane().add(txt_co);
        txt_co.setBounds(130, 250, 120, 23);

        txt_re.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        getContentPane().add(txt_re);
        txt_re.setBounds(130, 280, 120, 23);

        txt_de.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        getContentPane().add(txt_de);
        txt_de.setBounds(130, 310, 120, 23);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("fournisseur:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(290, 250, 90, 17);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("remise %:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(290, 280, 80, 17);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("prix:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(290, 310, 60, 17);

        jLabel10.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jLabel10.setText("rechercher par catégorie:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(490, 190, 190, 23);

        txt_fo.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        getContentPane().add(txt_fo);
        txt_fo.setBounds(390, 250, 110, 23);

        txt_rm.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        getContentPane().add(txt_rm);
        txt_rm.setBounds(390, 280, 110, 23);

        txt_pr.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        getContentPane().add(txt_pr);
        txt_pr.setBounds(390, 310, 110, 23);

        com_rech.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "id", "code_produit", "reférence", "désignation", "rangement", "fournisseur", "remise", "prix", "stock", " " }));
        getContentPane().add(com_rech);
        com_rech.setBounds(500, 220, 180, 20);

        jButton5.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jButton5.setText("recherche");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(510, 280, 105, 31);

        txt_rech.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        txt_rech.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_rechActionPerformed(evt);
            }
        });
        getContentPane().add(txt_rech);
        txt_rech.setBounds(620, 280, 90, 30);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("rangement:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 350, 90, 17);

        txt_ra.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        getContentPane().add(txt_ra);
        txt_ra.setBounds(130, 340, 120, 30);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText("stock:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(290, 340, 50, 17);

        txt_st.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        getContentPane().add(txt_st);
        txt_st.setBounds(390, 340, 110, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_rechActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_rechActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_rechActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        if(txt_co.getText().equals("") || txt_re.getText().equals("") || txt_de.getText().equals("") || txt_ra.getText().equals("")
                || txt_fo.getText().equals("") || txt_rm.getText().equals("") || txt_pr.getText().equals("") || txt_st.getText().equals("")){
            JOptionPane.showMessageDialog(this, "SVP entrer les informations completes");
        }else{
            String[] colon = {"code_produit", "reférence", "désignation", "rangement", "fournisseur", "remise", "prix", "stock"};
            String[] inf = {txt_co.getText(), txt_re.getText(), txt_de.getText(), txt_ra.getText(), txt_fo.getText(), txt_rm.getText(), txt_pr.getText(),
            txt_st.getText()};
            System.out.println(db.queryInsert("produit", colon, inf));
            table();    
            actualiser();    
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        if(txt_co.getText().equals("") || txt_re.getText().equals("") || txt_de.getText().equals("") || txt_ra.getText().equals("")
                || txt_fo.getText().equals("") || txt_rm.getText().equals("") || txt_pr.getText().equals("") || txt_st.getText().equals("")){
            JOptionPane.showMessageDialog(this, "SVP entrer les informations completes");
        }else{
            String[] colon = {"code_produit", "reférence", "désignation", "rangement", "fournisseur", "remise", "prix", "stock"};
            String[] inf = {txt_co.getText(), txt_re.getText(), txt_de.getText(), txt_ra.getText(), txt_fo.getText(), txt_rm.getText(), txt_pr.getText(),
                txt_st.getText()};
            String id = String.valueOf(table_prod.getValueAt(table_prod.getSelectedRow(), 0));
            System.out.println(db.queryUpdate("produit", colon, inf, "id='" + id + "'"));
            table();    
            actualiser(); 
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
         String id = String.valueOf(table_prod.getValueAt(table_prod.getSelectedRow(), 0));
        if(JOptionPane.showConfirmDialog(this, "voulez-vous vraiment supprimer", "attention!!!", 
                JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION){
            db.queryDelete("produit", "id=" + id);
        }else{
            return;
        }
        table();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        
        actualiser();
        table();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void table_prodMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_prodMouseClicked
        
        txt_co.setText(String.valueOf(table_prod.getValueAt(table_prod.getSelectedRow(), 0)));
        txt_re.setText(String.valueOf(table_prod.getValueAt(table_prod.getSelectedRow(), 1)));
        txt_de.setText(String.valueOf(table_prod.getValueAt(table_prod.getSelectedRow(), 2)));
        txt_ra.setText(String.valueOf(table_prod.getValueAt(table_prod.getSelectedRow(), 3)));
        txt_fo.setText(String.valueOf(table_prod.getValueAt(table_prod.getSelectedRow(), 4)));
        txt_rm.setText(String.valueOf(table_prod.getValueAt(table_prod.getSelectedRow(), 5)));
        txt_pr.setText(String.valueOf(table_prod.getValueAt(table_prod.getSelectedRow(), 6)));
        txt_st.setText(String.valueOf(table_prod.getValueAt(table_prod.getSelectedRow(), 7)));
        
    }//GEN-LAST:event_table_prodMouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        
         if(txt_rech.getText().equals("")){//si le textfield de recherche est vide le prog va affivher SVP entrer quelque chose
            JOptionPane.showMessageDialog(this, "SVP entrer quelque chose");
        }else{
            if(com_rech.getSelectedItem().equals("id")){
                rs = db.querySelectAll("produit", "id LIKE '%" + txt_rech.getText() + "%' ");
                table_prod.setModel(new ResultSetTableModel(rs));
            }else if(com_rech.getSelectedItem().equals("code_produit")){
                rs = db.querySelectAll("produit", "code_produit LIKE '%" + txt_rech.getText() + "%' ");
                table_prod.setModel(new ResultSetTableModel(rs));
            }else if(com_rech.getSelectedItem().equals("reférnce")){
                rs = db.querySelectAll("produit", "reférnce LIKE '%" + txt_rech.getText() + "%' ");
                table_prod.setModel(new ResultSetTableModel(rs));
            }else if(com_rech.getSelectedItem().equals("désignation")){
                rs = db.querySelectAll("produit", "désignation LIKE '%" + txt_rech.getText() + "%' ");
                table_prod.setModel(new ResultSetTableModel(rs));
            }else if(com_rech.getSelectedItem().equals("rangement")){
                rs = db.querySelectAll("produit", "rangement LIKE '%" + txt_rech.getText() + "%' ");
                table_prod.setModel(new ResultSetTableModel(rs));
            }else if(com_rech.getSelectedItem().equals("fournisseur")){
                rs = db.querySelectAll("produit", "fournisseur LIKE '%" + txt_rech.getText() + "%' ");
                table_prod.setModel(new ResultSetTableModel(rs));
            }else if(com_rech.getSelectedItem().equals("remise")){
                rs = db.querySelectAll("produit", "remise LIKE '%" + txt_rech.getText() + "%' ");
                table_prod.setModel(new ResultSetTableModel(rs));
            }else if(com_rech.getSelectedItem().equals("prix")){
                rs = db.querySelectAll("produit", "stock LIKE '%" + txt_rech.getText() + "%' ");
                table_prod.setModel(new ResultSetTableModel(rs));
            }else if(com_rech.getSelectedItem().equals("prix")){
                rs = db.querySelectAll("produit", "stock LIKE '%" + txt_rech.getText() + "%' ");
                table_prod.setModel(new ResultSetTableModel(rs));
            }
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Produit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Produit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Produit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Produit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Produit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> com_rech;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_prod;
    private javax.swing.JTextField txt_co;
    private javax.swing.JTextField txt_de;
    private javax.swing.JTextField txt_fo;
    private javax.swing.JTextField txt_pr;
    private javax.swing.JTextField txt_ra;
    private javax.swing.JTextField txt_re;
    private javax.swing.JTextField txt_rech;
    private javax.swing.JTextField txt_rm;
    private javax.swing.JTextField txt_st;
    // End of variables declaration//GEN-END:variables
}
