
package base_de_données;

import application_gestion_de_stock.Application_gestion_de_stock;
import application_gestion_de_stock.Parameter;
import application_gestion_de_stock.ResultSetTableModel;
import java.sql.*;
import javax.swing.JOptionPane;


public class Utilisateur extends javax.swing.JFrame {
//declaration
    ResultSet rs;
    Application_gestion_de_stock db;
   
    public Utilisateur() {
        db = new Application_gestion_de_stock(new Parameter().HOST_DB, new Parameter().USERNAME_DB,
                   new Parameter().PASSWORD_DB, new Parameter().IPHOST, new Parameter().PORT);
        
        initComponents();
        table();
    }    
    
    //fonction table
        public void table() {
            String a[] = {"id", "id_user", "username", "password", "type"};
            rs = db.querySelect(a, "utilisateur");
            table_user.setModel(new ResultSetTableModel(rs));    
        }
        void actualiser() {
            txt_id.setText("");
            txt_us.setText("");
            txt_pa.setText("");
            com_ty.setSelectedItem("Tyyyyyyype");
        }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_user = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        txt_us = new javax.swing.JTextField();
        txt_pa = new javax.swing.JTextField();
        txt_rech = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        com_ty = new javax.swing.JComboBox();
        com_rech = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(525, 435));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Calibri", 3, 36)); // NOI18N
        jLabel1.setText("utilisateur");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(180, 10, 153, 44);

        table_user.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "id", "id_user", "username", "password", "type"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_user.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_userMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_user);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 60, 490, 100);

        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton1.setText("Ajouter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(20, 200, 90, 31);

        jButton2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton2.setText("Modifier");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(130, 200, 100, 31);

        jButton3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton3.setText("Supprimer");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(250, 200, 107, 31);

        jButton4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton4.setText("Actualiser");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(370, 200, 120, 30);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("id_user:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 270, 60, 17);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("username:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 300, 70, 17);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("password:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 330, 70, 17);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("type:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 370, 60, 17);

        txt_id.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(txt_id);
        txt_id.setBounds(130, 270, 90, 23);

        txt_us.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_us.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usActionPerformed(evt);
            }
        });
        getContentPane().add(txt_us);
        txt_us.setBounds(130, 300, 90, 23);

        txt_pa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(txt_pa);
        txt_pa.setBounds(130, 330, 90, 23);

        txt_rech.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(txt_rech);
        txt_rech.setBounds(380, 320, 120, 30);

        jButton5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton5.setText("Recherche");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(250, 320, 110, 30);

        com_ty.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "directeur", "Caisier" }));
        getContentPane().add(com_ty);
        com_ty.setBounds(130, 360, 90, 30);

        com_rech.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "id_user", "username", "password", "type" }));
        getContentPane().add(com_rech);
        com_rech.setBounds(390, 270, 110, 30);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setText("rechercher par catégorie:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(240, 270, 150, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_usActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_usActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        if(txt_id.getText().equals("") || txt_us.getText().equals("") || txt_pa.getText().equals("")
                || com_ty.getSelectedItem().equals("Tyyyyyyype")){
            JOptionPane.showMessageDialog(this, "SVP entrer les informations completes");
        }else{
            String[] colon = {"id_user", "username", "password", "Type"};
            String[] inf = {txt_id.getText(), txt_us.getText(), txt_pa.getText(), com_ty.getSelectedItem().toString()};
            System.out.println(db.queryInsert("utilisateur", colon, inf));
            table();    
            actualiser();    
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        if(txt_id.getText().equals("") || txt_us.getText().equals("") || txt_pa.getText().equals("")
                || com_ty.getSelectedItem().equals("Type")){
            JOptionPane.showMessageDialog(this, "SVP entrer les informations completes");
        }else{
            String[] colon = {"id_user", "username", "password", "Tyyyyyyype"};
            String[] inf = {txt_id.getText(), txt_us.getText(), txt_pa.getText(), com_ty.getSelectedItem().toString()};
            String id = String.valueOf(table_user.getValueAt(table_user.getSelectedRow(), 0));
            System.out.println(db.queryUpdate("utilisateur", colon, inf, "id='" + id + "'"));
            table();    
            actualiser(); 
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String id = String.valueOf(table_user.getValueAt(table_user.getSelectedRow(), 0));
        if(JOptionPane.showConfirmDialog(this, "voulez-vous vraiment supprimer", "attention!!!", 
                JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION){
            db.queryDelete("utilisateur", "id=" + id);
        }else{
            return;
        }
        table();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
      table();
      actualiser();
       
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        
        if(txt_rech.getText().equals("")){//si le textfield de recherche est vide le prog va affivher SVP entrer quelque chose
            JOptionPane.showMessageDialog(this, "SVP entrer quelque chose");
        }else{
            if(com_rech.getSelectedItem().equals("id_user")){
                rs = db.querySelectAll("utilisateur", "id_user LIKE '%" + txt_rech.getText() + "%' ");
                table_user.setModel(new ResultSetTableModel(rs));
            }else if(com_rech.getSelectedItem().equals("username")){
                rs = db.querySelectAll("utilisateur", "username LIKE '%" + txt_rech.getText() + "%' ");
                table_user.setModel(new ResultSetTableModel(rs));
            }else if(com_rech.getSelectedItem().equals("password")){
                rs = db.querySelectAll("utilisateur", "password LIKE '%" + txt_rech.getText() + "%' ");
                table_user.setModel(new ResultSetTableModel(rs));
            }else if(com_rech.getSelectedItem().equals("type")){
                rs = db.querySelectAll("utilisateur", "type LIKE '%" + txt_rech.getText() + "%' ");
                table_user.setModel(new ResultSetTableModel(rs));
            }
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void table_userMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_userMouseClicked
        txt_id.setText(String.valueOf(table_user.getValueAt(table_user.getSelectedRow(), 1)));
        txt_us.setText(String.valueOf(table_user.getValueAt(table_user.getSelectedRow(), 2)));
        txt_pa.setText(String.valueOf(table_user.getValueAt(table_user.getSelectedRow(), 3)));
        com_ty.setSelectedItem(String.valueOf(table_user.getValueAt(table_user.getSelectedRow(), 4)));
    }//GEN-LAST:event_table_userMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Utilisateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Utilisateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Utilisateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Utilisateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Utilisateur().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox com_rech;
    private javax.swing.JComboBox com_ty;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_user;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_pa;
    private javax.swing.JTextField txt_rech;
    private javax.swing.JTextField txt_us;
    // End of variables declaration//GEN-END:variables
}
